### ISSUE TITLE
Paperclip deprecated

### ISSUE THREAD

**Issue by Faq** [tf/paperclip-nginx-upload#2]
Hello, as original project is deprecated, but continue to live on different gem [kt-paperclip](https://github.com/kreeti/kt-paperclip), would it be possible to update yours gem dependency to it?

**Comment by tf** [comment]
We could release that as version 2.0. I'd be happy to merge a PR that

* updates the dependency in the gemspec
* adds a note to the README to use version 1 with `paperclip` and version 2 with `kt-paperclip` 
* has been tested to actually work with `kt-paperclip`
